from building import *

cwd = GetCurrentDir()

src = Glob("./*.c")
path = [cwd, os.path.join(cwd, "../include")]

group = DefineGroup(
    "Drivers", src, depend=["BSP_USING_BOARD_TESTBOARD_525"], CPPPATH=path
)

if GetDepend("BSP_USING_BOARD_TESTBOARD_525"):
    group = group + SConscript("../testboard_525_base/script/SConscript")

Return("group")
